package buffet.ui.ban;

import buffet.dao.BanDAO;
import buffet.model.Ban;
import buffet.utils.XAuth;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author duyplus
 */
public class FrmBanJD extends javax.swing.JDialog {

    public static String NutBan = null;
    BanDAO dao = new BanDAO();

    /**
     * Creates new form QLBanJD
     *
     * @param parent
     * @param modal
     */
    public FrmBanJD(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    private void init() {
        setLocationRelativeTo(null);
        jspBan.getVerticalScrollBar().setUnitIncrement(16);

        setBackground(btnBan1.getToolTipText(), btnBan1);
        setBackground(btnBan2.getToolTipText(), btnBan2);
        setBackground(btnBan3.getToolTipText(), btnBan3);
        setBackground(btnBan4.getToolTipText(), btnBan4);
        setBackground(btnBan5.getToolTipText(), btnBan5);
        setBackground(btnBan6.getToolTipText(), btnBan6);
        setBackground(btnBan7.getToolTipText(), btnBan7);
        setBackground(btnBan8.getToolTipText(), btnBan8);
        setBackground(btnBan9.getToolTipText(), btnBan9);
        setBackground(btnBan10.getToolTipText(), btnBan10);
        setBackground(btnBan11.getToolTipText(), btnBan11);
        setBackground(btnBan12.getToolTipText(), btnBan12);
        setBackground(btnBan13.getToolTipText(), btnBan13);
        setBackground(btnBan14.getToolTipText(), btnBan14);
        setBackground(btnBan15.getToolTipText(), btnBan15);
        setBackground(btnBan16.getToolTipText(), btnBan16);
        setBackground(btnBan17.getToolTipText(), btnBan17);
        setBackground(btnBan18.getToolTipText(), btnBan18);
        setBackground(btnBan19.getToolTipText(), btnBan19);
        setBackground(btnBan20.getToolTipText(), btnBan20);
        setBackground(btnBan21.getToolTipText(), btnBan21);
        setBackground(btnBan22.getToolTipText(), btnBan22);
        setBackground(btnBan23.getToolTipText(), btnBan23);
        setBackground(btnBan24.getToolTipText(), btnBan24);
        setBackground(btnBan25.getToolTipText(), btnBan25);
        setBackground(btnBan26.getToolTipText(), btnBan26);
        setBackground(btnBan27.getToolTipText(), btnBan27);
        setBackground(btnBan28.getToolTipText(), btnBan28);
        setBackground(btnBan29.getToolTipText(), btnBan29);
        setBackground(btnBan30.getToolTipText(), btnBan30);
    }

    private void setBackground(String soban, JButton btn) {
        try {
            ImageIcon iconred = new ImageIcon(getClass().getResource("/icons/table-red.png"));
            ImageIcon iconblue = new ImageIcon(getClass().getResource("/icons/table-blue.png"));

            List<Ban> bans = dao.selectAll();
            for (int i = 0; i < bans.size(); i++) {
                String maban = (String) bans.get(i).getMaBan();
                if (maban.equals(soban)) {
                    btn.setIcon(iconred);
                    return;
                } else if (!maban.equals(soban)) {
                    btn.setIcon(iconblue);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void openCT() {
        this.dispose();
        new FrmBanCTJD().setVisible(true);
    }

    private void showName() {
        lblStaff.setText(XAuth.user.getTaiKhoan());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pblBan = new javax.swing.JPanel();
        lblExit = new javax.swing.JLabel();
        pnlSidebar = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        pnlSideBody = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        pnlStaff = new javax.swing.JPanel();
        lblStaff = new javax.swing.JLabel();
        pnlFoot = new javax.swing.JPanel();
        lblFoot = new javax.swing.JLabel();
        jspBan = new javax.swing.JScrollPane();
        pnlChonBan = new javax.swing.JPanel();
        btnBan1 = new javax.swing.JButton();
        btnBan2 = new javax.swing.JButton();
        btnBan3 = new javax.swing.JButton();
        btnBan4 = new javax.swing.JButton();
        btnBan5 = new javax.swing.JButton();
        btnBan6 = new javax.swing.JButton();
        btnBan7 = new javax.swing.JButton();
        btnBan8 = new javax.swing.JButton();
        btnBan9 = new javax.swing.JButton();
        btnBan10 = new javax.swing.JButton();
        btnBan11 = new javax.swing.JButton();
        btnBan12 = new javax.swing.JButton();
        btnBan13 = new javax.swing.JButton();
        btnBan14 = new javax.swing.JButton();
        btnBan15 = new javax.swing.JButton();
        btnBan16 = new javax.swing.JButton();
        btnBan17 = new javax.swing.JButton();
        btnBan18 = new javax.swing.JButton();
        btnBan19 = new javax.swing.JButton();
        btnBan20 = new javax.swing.JButton();
        btnBan21 = new javax.swing.JButton();
        btnBan22 = new javax.swing.JButton();
        btnBan23 = new javax.swing.JButton();
        btnBan24 = new javax.swing.JButton();
        btnBan25 = new javax.swing.JButton();
        btnBan26 = new javax.swing.JButton();
        btnBan27 = new javax.swing.JButton();
        btnBan28 = new javax.swing.JButton();
        btnBan29 = new javax.swing.JButton();
        btnBan30 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("QUẢN LÝ BÀN");
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pblBan.setBackground(new java.awt.Color(56, 182, 255));
        pblBan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblExit.setFont(new java.awt.Font("Be Vietnam Pro", 1, 24)); // NOI18N
        lblExit.setForeground(new java.awt.Color(255, 255, 255));
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setText("x");
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });

        pnlSidebar.setBackground(new java.awt.Color(255, 255, 255));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo-app.png"))); // NOI18N

        pnlSideBody.setBackground(new java.awt.Color(255, 255, 255));

        lblIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-user.png"))); // NOI18N

        pnlStaff.setBackground(new java.awt.Color(255, 255, 255));
        pnlStaff.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lblStaff.setFont(new java.awt.Font("Be Vietnam Pro", 1, 30)); // NOI18N
        lblStaff.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlStaffLayout = new javax.swing.GroupLayout(pnlStaff);
        pnlStaff.setLayout(pnlStaffLayout);
        pnlStaffLayout.setHorizontalGroup(
            pnlStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStaffLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStaff, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlStaffLayout.setVerticalGroup(
            pnlStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStaffLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStaff, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlSideBodyLayout = new javax.swing.GroupLayout(pnlSideBody);
        pnlSideBody.setLayout(pnlSideBodyLayout);
        pnlSideBodyLayout.setHorizontalGroup(
            pnlSideBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSideBodyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
            .addComponent(lblIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlSideBodyLayout.setVerticalGroup(
            pnlSideBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideBodyLayout.createSequentialGroup()
                .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pnlFoot.setBackground(new java.awt.Color(0, 0, 0));
        pnlFoot.setPreferredSize(new java.awt.Dimension(256, 55));

        lblFoot.setFont(new java.awt.Font("Be Vietnam Pro", 1, 24)); // NOI18N
        lblFoot.setForeground(new java.awt.Color(255, 255, 255));
        lblFoot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFoot.setText("CHỌN BÀN");

        javax.swing.GroupLayout pnlFootLayout = new javax.swing.GroupLayout(pnlFoot);
        pnlFoot.setLayout(pnlFootLayout);
        pnlFootLayout.setHorizontalGroup(
            pnlFootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFootLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(lblFoot, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFootLayout.setVerticalGroup(
            pnlFootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFoot, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlSidebarLayout = new javax.swing.GroupLayout(pnlSidebar);
        pnlSidebar.setLayout(pnlSidebarLayout);
        pnlSidebarLayout.setHorizontalGroup(
            pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSidebarLayout.createSequentialGroup()
                .addGroup(pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlSideBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(pnlFoot, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        pnlSidebarLayout.setVerticalGroup(
            pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSidebarLayout.createSequentialGroup()
                .addComponent(lblLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSideBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlFoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlChonBan.setBackground(new java.awt.Color(56, 182, 255));

        btnBan1.setBackground(new java.awt.Color(56, 182, 255));
        btnBan1.setFont(new java.awt.Font("Be Vietnam Pro", 0, 48)); // NOI18N
        btnBan1.setForeground(new java.awt.Color(255, 255, 255));
        btnBan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/table-blue.png"))); // NOI18N
        btnBan1.setText("01");
        btnBan1.setToolTipText("01");
        btnBan1.setBorderPainted(false);
        btnBan1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan1ActionPerformed(evt);
            }
        });

        btnBan2.setBackground(new java.awt.Color(56, 182, 255));
        btnBan2.setFont(new java.awt.Font("Be Vietnam Pro", 0, 48)); // NOI18N
        btnBan2.setForeground(new java.awt.Color(255, 255, 255));
        btnBan2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/table-blue.png"))); // NOI18N
        btnBan2.setText("02");
        btnBan2.setToolTipText("02");
        btnBan2.setBorderPainted(false);
        btnBan2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan2ActionPerformed(evt);
            }
        });

        btnBan3.setBackground(new java.awt.Color(56, 182, 255));
        btnBan3.setFont(new java.awt.Font("Be Vietnam Pro", 0, 48)); // NOI18N
        btnBan3.setForeground(new java.awt.Color(255, 255, 255));
        btnBan3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/table-blue.png"))); // NOI18N
        btnBan3.setText("03");
        btnBan3.setToolTipText("03");
        btnBan3.setBorderPainted(false);
        btnBan3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBan3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan3ActionPerformed(evt);
            }
        });

        btnBan4.setBackground(new java.awt.Color(56, 182, 255));
        btnBan4.setFont(new java.awt.Font("Be Vietnam Pro", 0, 48)); // NOI18N
        btnBan4.setForeground(new java.awt.Color(255, 255, 255));
        btnBan4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/table-blue.png"))); // NOI18N
        btnBan4.setText("04");
        btnBan4.setToolTipText("04");
        btnBan4.setBorderPainted(false);
        btnBan4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBan4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan4ActionPerformed(evt);
            }
        });

        btnBan5.setBackground(new java.awt.Color(56, 182, 255));
        btnBan5.setFont(new java.awt.Font("Be Vietnam Pro", 0, 48)); // NOI18N
        btnBan5.setForeground(new java.awt.Color(255, 255, 255));
        btnBan5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/table-blue.png"))); // NOI18N
        btnBan5.setText("05");
        btnBan5.setToolTipText("05");
        btnBan5.setBorderPainted(false);
        btnBan5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBan5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan5ActionPerformed(evt);
            }
        });

        btnBan6.setBackground(new java.awt.Color(56, 182, 255));
        btnBan6.setFont(new java.awt.Font("Be Vietnam Pro", 0, 48)); // NOI18N
        btnBan6.setForeground(new java.awt.Color(255, 255, 255));
        btnBan6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/table-blue.png"))); // NOI18N
        btnBan6.setText("06");
        btnBan6.setToolTipText("06");
        btnBan6.setBorderPainted(false);
        btnBan6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBan6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan6ActionPerformed(evt);
            }
        });

        btnBan7.setBackground(new java.awt.Color(56, 182, 255));
        btnBan7.setFont(new java.awt.Font("Be Vietnam Pro", 0, 48)); // NOI18N
        btnBan7.setForeground(new java.awt.Color(255, 255, 255));
        btnBan7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/table-blue.png"))); // NOI18N
        btnBan7.setText("07");
        btnBan7.setToolTipText("07");
        btnBan7.setBorderPainted(false);
        btnBan7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBan7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan7ActionPerformed(evt);
            }
        });

        btnBan8.setBackground(new java.awt.Color(56, 182, 255));
        btnBan8.setFont(new java.awt.Font("Be Vietnam Pro", 0, 48)); // NOI18N
        btnBan8.setForeground(new java.awt.Color(255, 255, 255));
        btnBan8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/table-blue.png"))); // NOI18N
        btnBan8.setText("08");
        btnBan8.setToolTipText("08");
        btnBan8.setBorderPainted(false);
        btnBan8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBan8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan8ActionPerformed(evt);
            }
        });

        btnBan9.setBackground(new java.awt.Color(56, 182, 255));
        btnBan9.setFont(new java.awt.Font("Be Vietnam Pro", 0, 48)); // NOI18N
        btnBan9.setForeground(new java.awt.Color(255, 255, 255));
        btnBan9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/table-blue.png"))); // NOI18N
        btnBan9.setText("09");
        btnBan9.setToolTipText("09");
        btnBan9.setBorderPainted(false);
        btnBan9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBan9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan9ActionPerformed(evt);
            }
        });

        btnBan10.setBackground(new java.awt.Color(56, 182, 255));
        btnBan10.setFont(new java.awt.Font("Be Vietnam Pro", 0, 48)); // NOI18N
        btnBan10.setForeground(new java.awt.Color(255, 255, 255));
        btnBan10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/table-blue.png"))); // NOI18N
        btnBan10.setText("10");
        btnBan10.setToolTipText("10");
        btnBan10.setBorderPainted(false);
        btnBan10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBan10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan10ActionPerformed(evt);
            }
        });

        btnBan11.setBackground(new java.awt.Color(56, 182, 255));
        btnBan11.setFont(new java.awt.Font("Be Vietnam Pro", 0, 48)); // NOI18N
        btnBan11.setForeground(new java.awt.Color(255, 255, 255));
        btnBan11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/table-blue.png"))); // NOI18N
        btnBan11.setText("11");
        btnBan11.setToolTipText("11");
        btnBan11.setBorderPainted(false);
        btnBan11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBan11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan11ActionPerformed(evt);
            }
        });

        btnBan12.setBackground(new java.awt.Color(56, 182, 255));
        btnBan12.setFont(new java.awt.Font("Be Vietnam Pro", 0, 48)); // NOI18N
        btnBan12.setForeground(new java.awt.Color(255, 255, 255));
        btnBan12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/table-blue.png"))); // NOI18N
        btnBan12.setText("12");
        btnBan12.setToolTipText("12");
        btnBan12.setBorderPainted(false);
        btnBan12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBan12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan12ActionPerformed(evt);
            }
        });

        btnBan13.setBackground(new java.awt.Color(56, 182, 255));
        btnBan13.setFont(new java.awt.Font("Be Vietnam Pro", 0, 48)); // NOI18N
        btnBan13.setForeground(new java.awt.Color(255, 255, 255));
        btnBan13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/table-blue.png"))); // NOI18N
        btnBan13.setText("13");
        btnBan13.setToolTipText("13");
        btnBan13.setBorderPainted(false);
        btnBan13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBan13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan13ActionPerformed(evt);
            }
        });

        btnBan14.setBackground(new java.awt.Color(56, 182, 255));
        btnBan14.setFont(new java.awt.Font("Be Vietnam Pro", 0, 48)); // NOI18N
        btnBan14.setForeground(new java.awt.Color(255, 255, 255));
        btnBan14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/table-blue.png"))); // NOI18N
        btnBan14.setText("14");
        btnBan14.setToolTipText("14");
        btnBan14.setBorderPainted(false);
        btnBan14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBan14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan14ActionPerformed(evt);
            }
        });

        btnBan15.setBackground(new java.awt.Color(56, 182, 255));
        btnBan15.setFont(new java.awt.Font("Be Vietnam Pro", 0, 48)); // NOI18N
        btnBan15.setForeground(new java.awt.Color(255, 255, 255));
        btnBan15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/table-blue.png"))); // NOI18N
        btnBan15.setText("15");
        btnBan15.setToolTipText("15");
        btnBan15.setBorderPainted(false);
        btnBan15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBan15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan15ActionPerformed(evt);
            }
        });

        btnBan16.setBackground(new java.awt.Color(56, 182, 255));
        btnBan16.setFont(new java.awt.Font("Be Vietnam Pro", 0, 48)); // NOI18N
        btnBan16.setForeground(new java.awt.Color(255, 255, 255));
        btnBan16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/table-blue.png"))); // NOI18N
        btnBan16.setText("16");
        btnBan16.setToolTipText("16");
        btnBan16.setBorderPainted(false);
        btnBan16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBan16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan16ActionPerformed(evt);
            }
        });

        btnBan17.setBackground(new java.awt.Color(56, 182, 255));
        btnBan17.setFont(new java.awt.Font("Be Vietnam Pro", 0, 48)); // NOI18N
        btnBan17.setForeground(new java.awt.Color(255, 255, 255));
        btnBan17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/table-blue.png"))); // NOI18N
        btnBan17.setText("17");
        btnBan17.setToolTipText("17");
        btnBan17.setBorderPainted(false);
        btnBan17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBan17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan17ActionPerformed(evt);
            }
        });

        btnBan18.setBackground(new java.awt.Color(56, 182, 255));
        btnBan18.setFont(new java.awt.Font("Be Vietnam Pro", 0, 48)); // NOI18N
        btnBan18.setForeground(new java.awt.Color(255, 255, 255));
        btnBan18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/table-blue.png"))); // NOI18N
        btnBan18.setText("18");
        btnBan18.setToolTipText("18");
        btnBan18.setBorderPainted(false);
        btnBan18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBan18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan18ActionPerformed(evt);
            }
        });

        btnBan19.setBackground(new java.awt.Color(56, 182, 255));
        btnBan19.setFont(new java.awt.Font("Be Vietnam Pro", 0, 48)); // NOI18N
        btnBan19.setForeground(new java.awt.Color(255, 255, 255));
        btnBan19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/table-blue.png"))); // NOI18N
        btnBan19.setText("19");
        btnBan19.setToolTipText("19");
        btnBan19.setBorderPainted(false);
        btnBan19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBan19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan19ActionPerformed(evt);
            }
        });

        btnBan20.setBackground(new java.awt.Color(56, 182, 255));
        btnBan20.setFont(new java.awt.Font("Be Vietnam Pro", 0, 48)); // NOI18N
        btnBan20.setForeground(new java.awt.Color(255, 255, 255));
        btnBan20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/table-blue.png"))); // NOI18N
        btnBan20.setText("20");
        btnBan20.setToolTipText("20");
        btnBan20.setBorderPainted(false);
        btnBan20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBan20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan20ActionPerformed(evt);
            }
        });

        btnBan21.setBackground(new java.awt.Color(56, 182, 255));
        btnBan21.setFont(new java.awt.Font("Be Vietnam Pro", 0, 48)); // NOI18N
        btnBan21.setForeground(new java.awt.Color(255, 255, 255));
        btnBan21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/table-blue.png"))); // NOI18N
        btnBan21.setText("21");
        btnBan21.setToolTipText("21");
        btnBan21.setBorderPainted(false);
        btnBan21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBan21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan21ActionPerformed(evt);
            }
        });

        btnBan22.setBackground(new java.awt.Color(56, 182, 255));
        btnBan22.setFont(new java.awt.Font("Be Vietnam Pro", 0, 48)); // NOI18N
        btnBan22.setForeground(new java.awt.Color(255, 255, 255));
        btnBan22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/table-blue.png"))); // NOI18N
        btnBan22.setText("22");
        btnBan22.setToolTipText("22");
        btnBan22.setBorderPainted(false);
        btnBan22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBan22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan22ActionPerformed(evt);
            }
        });

        btnBan23.setBackground(new java.awt.Color(56, 182, 255));
        btnBan23.setFont(new java.awt.Font("Be Vietnam Pro", 0, 48)); // NOI18N
        btnBan23.setForeground(new java.awt.Color(255, 255, 255));
        btnBan23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/table-blue.png"))); // NOI18N
        btnBan23.setText("23");
        btnBan23.setToolTipText("23");
        btnBan23.setBorderPainted(false);
        btnBan23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBan23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan23ActionPerformed(evt);
            }
        });

        btnBan24.setBackground(new java.awt.Color(56, 182, 255));
        btnBan24.setFont(new java.awt.Font("Be Vietnam Pro", 0, 48)); // NOI18N
        btnBan24.setForeground(new java.awt.Color(255, 255, 255));
        btnBan24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/table-blue.png"))); // NOI18N
        btnBan24.setText("24");
        btnBan24.setToolTipText("24");
        btnBan24.setBorderPainted(false);
        btnBan24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBan24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan24ActionPerformed(evt);
            }
        });

        btnBan25.setBackground(new java.awt.Color(56, 182, 255));
        btnBan25.setFont(new java.awt.Font("Be Vietnam Pro", 0, 48)); // NOI18N
        btnBan25.setForeground(new java.awt.Color(255, 255, 255));
        btnBan25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/table-blue.png"))); // NOI18N
        btnBan25.setText("25");
        btnBan25.setToolTipText("25");
        btnBan25.setBorderPainted(false);
        btnBan25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBan25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan25ActionPerformed(evt);
            }
        });

        btnBan26.setBackground(new java.awt.Color(56, 182, 255));
        btnBan26.setFont(new java.awt.Font("Be Vietnam Pro", 0, 48)); // NOI18N
        btnBan26.setForeground(new java.awt.Color(255, 255, 255));
        btnBan26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/table-blue.png"))); // NOI18N
        btnBan26.setText("26");
        btnBan26.setToolTipText("26");
        btnBan26.setBorderPainted(false);
        btnBan26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBan26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan26ActionPerformed(evt);
            }
        });

        btnBan27.setBackground(new java.awt.Color(56, 182, 255));
        btnBan27.setFont(new java.awt.Font("Be Vietnam Pro", 0, 48)); // NOI18N
        btnBan27.setForeground(new java.awt.Color(255, 255, 255));
        btnBan27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/table-blue.png"))); // NOI18N
        btnBan27.setText("27");
        btnBan27.setToolTipText("27");
        btnBan27.setBorderPainted(false);
        btnBan27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBan27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan27ActionPerformed(evt);
            }
        });

        btnBan28.setBackground(new java.awt.Color(56, 182, 255));
        btnBan28.setFont(new java.awt.Font("Be Vietnam Pro", 0, 48)); // NOI18N
        btnBan28.setForeground(new java.awt.Color(255, 255, 255));
        btnBan28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/table-blue.png"))); // NOI18N
        btnBan28.setText("28");
        btnBan28.setToolTipText("28");
        btnBan28.setBorderPainted(false);
        btnBan28.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBan28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan28ActionPerformed(evt);
            }
        });

        btnBan29.setBackground(new java.awt.Color(56, 182, 255));
        btnBan29.setFont(new java.awt.Font("Be Vietnam Pro", 0, 48)); // NOI18N
        btnBan29.setForeground(new java.awt.Color(255, 255, 255));
        btnBan29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/table-blue.png"))); // NOI18N
        btnBan29.setText("29");
        btnBan29.setToolTipText("29");
        btnBan29.setBorderPainted(false);
        btnBan29.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBan29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan29ActionPerformed(evt);
            }
        });

        btnBan30.setBackground(new java.awt.Color(56, 182, 255));
        btnBan30.setFont(new java.awt.Font("Be Vietnam Pro", 0, 48)); // NOI18N
        btnBan30.setForeground(new java.awt.Color(255, 255, 255));
        btnBan30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/table-blue.png"))); // NOI18N
        btnBan30.setText("30");
        btnBan30.setToolTipText("30");
        btnBan30.setBorderPainted(false);
        btnBan30.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBan30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan30ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlChonBanLayout = new javax.swing.GroupLayout(pnlChonBan);
        pnlChonBan.setLayout(pnlChonBanLayout);
        pnlChonBanLayout.setHorizontalGroup(
            pnlChonBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChonBanLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pnlChonBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChonBanLayout.createSequentialGroup()
                        .addGroup(pnlChonBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBan13, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBan7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBan4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBan1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBan10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                        .addGroup(pnlChonBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBan14, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlChonBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnBan8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnBan5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnBan2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnBan11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(126, 126, 126)
                        .addGroup(pnlChonBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBan15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBan3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBan6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBan9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBan12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlChonBanLayout.createSequentialGroup()
                        .addGroup(pnlChonBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBan16, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBan19, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBan22, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(127, 127, 127)
                        .addGroup(pnlChonBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlChonBanLayout.createSequentialGroup()
                                .addComponent(btnBan23, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBan24, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlChonBanLayout.createSequentialGroup()
                                .addGroup(pnlChonBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBan17, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnBan20, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlChonBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnBan18, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnBan21, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pnlChonBanLayout.createSequentialGroup()
                        .addGroup(pnlChonBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlChonBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnBan29, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pnlChonBanLayout.createSequentialGroup()
                                    .addComponent(btnBan25, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(127, 127, 127)
                                    .addComponent(btnBan26, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnBan28, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlChonBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBan27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBan30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50))
        );
        pnlChonBanLayout.setVerticalGroup(
            pnlChonBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChonBanLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlChonBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlChonBanLayout.createSequentialGroup()
                        .addComponent(btnBan5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnBan8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnBan11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnBan14, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlChonBanLayout.createSequentialGroup()
                        .addGroup(pnlChonBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlChonBanLayout.createSequentialGroup()
                                .addGroup(pnlChonBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnBan1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlChonBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnBan3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnBan2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(35, 35, 35)
                                .addComponent(btnBan4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnBan6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(pnlChonBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBan7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBan9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(pnlChonBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBan10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBan12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(pnlChonBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBan13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBan15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 35, 35)
                .addGroup(pnlChonBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBan16, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlChonBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBan18, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBan17, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(pnlChonBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBan20, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBan19, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBan21, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(pnlChonBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBan23, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBan22, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBan24, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(pnlChonBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBan26, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBan25, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBan27, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(pnlChonBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBan28, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBan29, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBan30, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jspBan.setViewportView(pnlChonBan);

        javax.swing.GroupLayout pblBanLayout = new javax.swing.GroupLayout(pblBan);
        pblBan.setLayout(pblBanLayout);
        pblBanLayout.setHorizontalGroup(
            pblBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pblBanLayout.createSequentialGroup()
                .addGroup(pblBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pblBanLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pblBanLayout.createSequentialGroup()
                        .addComponent(jspBan, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addComponent(pnlSidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pblBanLayout.setVerticalGroup(
            pblBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pblBanLayout.createSequentialGroup()
                .addComponent(lblExit)
                .addGap(0, 0, 0)
                .addComponent(jspBan, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pblBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pblBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_lblExitMouseClicked

    private void btnBan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan1ActionPerformed
        // TODO add your handling code here:
        NutBan = null;
        NutBan = btnBan1.getToolTipText();
        openCT();
    }//GEN-LAST:event_btnBan1ActionPerformed

    private void btnBan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan2ActionPerformed
        // TODO add your handling code here:
        NutBan = null;
        NutBan = btnBan2.getToolTipText();
        openCT();
    }//GEN-LAST:event_btnBan2ActionPerformed

    private void btnBan3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan3ActionPerformed
        // TODO add your handling code here:
        NutBan = null;
        NutBan = btnBan3.getToolTipText();
        openCT();
    }//GEN-LAST:event_btnBan3ActionPerformed

    private void btnBan4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan4ActionPerformed
        // TODO add your handling code here:
        NutBan = null;
        NutBan = btnBan4.getToolTipText();
        openCT();
    }//GEN-LAST:event_btnBan4ActionPerformed

    private void btnBan5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan5ActionPerformed
        // TODO add your handling code here:
        NutBan = null;
        NutBan = btnBan5.getToolTipText();
        openCT();
    }//GEN-LAST:event_btnBan5ActionPerformed

    private void btnBan6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan6ActionPerformed
        // TODO add your handling code here:
        NutBan = null;
        NutBan = btnBan6.getToolTipText();
        openCT();
    }//GEN-LAST:event_btnBan6ActionPerformed

    private void btnBan7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan7ActionPerformed
        // TODO add your handling code here:
        NutBan = null;
        NutBan = btnBan7.getToolTipText();
        openCT();
    }//GEN-LAST:event_btnBan7ActionPerformed

    private void btnBan8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan8ActionPerformed
        // TODO add your handling code here:
        NutBan = null;
        NutBan = btnBan8.getToolTipText();
        openCT();
    }//GEN-LAST:event_btnBan8ActionPerformed

    private void btnBan9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan9ActionPerformed
        // TODO add your handling code here:
        NutBan = null;
        NutBan = btnBan9.getToolTipText();
        openCT();
    }//GEN-LAST:event_btnBan9ActionPerformed

    private void btnBan10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan10ActionPerformed
        // TODO add your handling code here:
        NutBan = null;
        NutBan = btnBan10.getToolTipText();
        openCT();
    }//GEN-LAST:event_btnBan10ActionPerformed

    private void btnBan11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan11ActionPerformed
        // TODO add your handling code here:
        NutBan = null;
        NutBan = btnBan11.getToolTipText();
        openCT();
    }//GEN-LAST:event_btnBan11ActionPerformed

    private void btnBan12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan12ActionPerformed
        // TODO add your handling code here:
        NutBan = null;
        NutBan = btnBan12.getToolTipText();
        openCT();
    }//GEN-LAST:event_btnBan12ActionPerformed

    private void btnBan13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan13ActionPerformed
        // TODO add your handling code here:
        NutBan = null;
        NutBan = btnBan13.getToolTipText();
        openCT();
    }//GEN-LAST:event_btnBan13ActionPerformed

    private void btnBan14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan14ActionPerformed
        // TODO add your handling code here:
        NutBan = null;
        NutBan = btnBan14.getToolTipText();
        openCT();
    }//GEN-LAST:event_btnBan14ActionPerformed

    private void btnBan15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan15ActionPerformed
        // TODO add your handling code here:
        NutBan = null;
        NutBan = btnBan15.getToolTipText();
        openCT();
    }//GEN-LAST:event_btnBan15ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.showName();
    }//GEN-LAST:event_formWindowOpened

    private void btnBan16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan16ActionPerformed
        // TODO add your handling code here:
        NutBan = null;
        NutBan = btnBan16.getToolTipText();
        openCT();
    }//GEN-LAST:event_btnBan16ActionPerformed

    private void btnBan17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan17ActionPerformed
        // TODO add your handling code here:
        NutBan = null;
        NutBan = btnBan17.getToolTipText();
        openCT();
    }//GEN-LAST:event_btnBan17ActionPerformed

    private void btnBan18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan18ActionPerformed
        // TODO add your handling code here:
        NutBan = null;
        NutBan = btnBan18.getToolTipText();
        openCT();
    }//GEN-LAST:event_btnBan18ActionPerformed

    private void btnBan19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan19ActionPerformed
        // TODO add your handling code here:
        NutBan = null;
        NutBan = btnBan19.getToolTipText();
        openCT();
    }//GEN-LAST:event_btnBan19ActionPerformed

    private void btnBan20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan20ActionPerformed
        // TODO add your handling code here:
        NutBan = null;
        NutBan = btnBan20.getToolTipText();
        openCT();
    }//GEN-LAST:event_btnBan20ActionPerformed

    private void btnBan21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan21ActionPerformed
        // TODO add your handling code here:
        NutBan = null;
        NutBan = btnBan21.getToolTipText();
        openCT();
    }//GEN-LAST:event_btnBan21ActionPerformed

    private void btnBan22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan22ActionPerformed
        // TODO add your handling code here:
        NutBan = null;
        NutBan = btnBan22.getToolTipText();
        openCT();
    }//GEN-LAST:event_btnBan22ActionPerformed

    private void btnBan23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan23ActionPerformed
        // TODO add your handling code here:
        NutBan = null;
        NutBan = btnBan23.getToolTipText();
        openCT();
    }//GEN-LAST:event_btnBan23ActionPerformed

    private void btnBan24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan24ActionPerformed
        // TODO add your handling code here:
        NutBan = null;
        NutBan = btnBan24.getToolTipText();
        openCT();
    }//GEN-LAST:event_btnBan24ActionPerformed

    private void btnBan25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBan25ActionPerformed

    private void btnBan26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBan26ActionPerformed

    private void btnBan27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBan27ActionPerformed

    private void btnBan28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBan28ActionPerformed

    private void btnBan29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBan29ActionPerformed

    private void btnBan30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBan30ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBan1;
    private javax.swing.JButton btnBan10;
    private javax.swing.JButton btnBan11;
    private javax.swing.JButton btnBan12;
    private javax.swing.JButton btnBan13;
    private javax.swing.JButton btnBan14;
    private javax.swing.JButton btnBan15;
    private javax.swing.JButton btnBan16;
    private javax.swing.JButton btnBan17;
    private javax.swing.JButton btnBan18;
    private javax.swing.JButton btnBan19;
    private javax.swing.JButton btnBan2;
    private javax.swing.JButton btnBan20;
    private javax.swing.JButton btnBan21;
    private javax.swing.JButton btnBan22;
    private javax.swing.JButton btnBan23;
    private javax.swing.JButton btnBan24;
    private javax.swing.JButton btnBan25;
    private javax.swing.JButton btnBan26;
    private javax.swing.JButton btnBan27;
    private javax.swing.JButton btnBan28;
    private javax.swing.JButton btnBan29;
    private javax.swing.JButton btnBan3;
    private javax.swing.JButton btnBan30;
    private javax.swing.JButton btnBan4;
    private javax.swing.JButton btnBan5;
    private javax.swing.JButton btnBan6;
    private javax.swing.JButton btnBan7;
    private javax.swing.JButton btnBan8;
    private javax.swing.JButton btnBan9;
    private javax.swing.JScrollPane jspBan;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblFoot;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblStaff;
    private javax.swing.JPanel pblBan;
    private javax.swing.JPanel pnlChonBan;
    private javax.swing.JPanel pnlFoot;
    private javax.swing.JPanel pnlSideBody;
    private javax.swing.JPanel pnlSidebar;
    private javax.swing.JPanel pnlStaff;
    // End of variables declaration//GEN-END:variables
}
