package buffet.ui;

import buffet.dao.DoanhThuDAO;
import buffet.utils.XAuth;
import buffet.utils.XDate;
import buffet.utils.XHelper;
import java.awt.Dimension;
import java.awt.Font;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author duyplus
 */
public class FrmDoanhThuJD extends javax.swing.JDialog {

    DoanhThuDAO dtdao = new DoanhThuDAO();

    /**
     * Creates new form QLDoanhThuJD
     *
     * @param parent
     * @param modal
     */
    public FrmDoanhThuJD(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    private void init() {
        setLocationRelativeTo(null);
        DefaultTableCellRenderer render = new DefaultTableCellRenderer();
        render.setHorizontalAlignment(javax.swing.JLabel.CENTER);

        TableColumnModel ngay = tblNgay.getColumnModel();
        ngay.getColumn(0).setCellRenderer(render);
        ngay.getColumn(1).setCellRenderer(render);
        ngay.getColumn(2).setCellRenderer(render);
        ngay.getColumn(3).setCellRenderer(render);

        TableColumnModel thang = tblThang.getColumnModel();
        thang.getColumn(0).setCellRenderer(render);
        thang.getColumn(1).setCellRenderer(render);
        thang.getColumn(2).setCellRenderer(render);
        thang.getColumn(3).setCellRenderer(render);

        TableColumnModel nam = tblNam.getColumnModel();
        nam.getColumn(0).setCellRenderer(render);
        nam.getColumn(1).setCellRenderer(render);
        nam.getColumn(2).setCellRenderer(render);
        nam.getColumn(3).setCellRenderer(render);

        Font font = new Font("Be Vietnam Pro", Font.PLAIN, 16);
        tblNgay.getTableHeader().setFont(font);
        tblNgay.getTableHeader().setPreferredSize(new Dimension(100, 35));
        tblThang.getTableHeader().setFont(font);
        tblThang.getTableHeader().setPreferredSize(new Dimension(100, 35));
        tblNam.getTableHeader().setFont(font);
        tblNam.getTableHeader().setPreferredSize(new Dimension(100, 35));
    }

    private void fillTableDTNgay() {
        try {
            DefaultTableModel model = (DefaultTableModel) tblNgay.getModel();
            model.setRowCount(0);
            List<Object[]> list = dtdao.getDoanhThuNgay();
            for (Object[] row : list) {
                model.addRow(new Object[]{
                    XDate.toString((Date) row[0]), row[1], row[2],
                    XHelper.commafy(String.valueOf(row[3]))
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void fillTableDTThang() {
        try {
            DefaultTableModel model = (DefaultTableModel) tblThang.getModel();
            model.setRowCount(0);
            List<Object[]> list = dtdao.getDoanhThuThang();
            for (Object[] row : list) {
                model.addRow(new Object[]{
                    row[0], row[1], row[2],
                    XHelper.commafy(String.valueOf(row[3]))
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void fillTableDTNam() {
        try {
            DefaultTableModel model = (DefaultTableModel) tblNam.getModel();
            model.setRowCount(0);
            List<Object[]> list = dtdao.getDoanhThuNam();
            for (Object[] row : list) {
                model.addRow(new Object[]{
                    row[0], row[1], row[2],
                    XHelper.commafy(String.valueOf(row[3]))
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void showName() {
        lblStaff.setText(XAuth.user.getTaiKhoan());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pblBan = new javax.swing.JPanel();
        pnlSidebar = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        pnlSideBody = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        pnlStaff = new javax.swing.JPanel();
        lblStaff = new javax.swing.JLabel();
        pnlFoot = new javax.swing.JPanel();
        lblFoot = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        jtpDoanhThu = new javax.swing.JTabbedPane();
        pnlNgay = new javax.swing.JPanel();
        jspNgay = new javax.swing.JScrollPane();
        tblNgay = new javax.swing.JTable();
        btnXuatNgay = new javax.swing.JButton();
        txtSearchNgay = new javax.swing.JTextField();
        pnlThang = new javax.swing.JPanel();
        jspThang = new javax.swing.JScrollPane();
        tblThang = new javax.swing.JTable();
        btnXuatThang = new javax.swing.JButton();
        txtSearchThang = new javax.swing.JTextField();
        pnlNam = new javax.swing.JPanel();
        jspNam = new javax.swing.JScrollPane();
        tblNam = new javax.swing.JTable();
        btnXuatNam = new javax.swing.JButton();
        txtSearchNam = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("QUẢN LÝ DOANH THU");
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pblBan.setBackground(new java.awt.Color(56, 182, 255));
        pblBan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pnlSidebar.setBackground(new java.awt.Color(255, 255, 255));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo-app.png"))); // NOI18N

        pnlSideBody.setBackground(new java.awt.Color(255, 255, 255));

        lblIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-user.png"))); // NOI18N

        pnlStaff.setBackground(new java.awt.Color(255, 255, 255));
        pnlStaff.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lblStaff.setFont(new java.awt.Font("Be Vietnam Pro", 1, 30)); // NOI18N
        lblStaff.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlStaffLayout = new javax.swing.GroupLayout(pnlStaff);
        pnlStaff.setLayout(pnlStaffLayout);
        pnlStaffLayout.setHorizontalGroup(
            pnlStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStaffLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStaff, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlStaffLayout.setVerticalGroup(
            pnlStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStaffLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStaff, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlSideBodyLayout = new javax.swing.GroupLayout(pnlSideBody);
        pnlSideBody.setLayout(pnlSideBodyLayout);
        pnlSideBodyLayout.setHorizontalGroup(
            pnlSideBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSideBodyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addComponent(lblIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlSideBodyLayout.setVerticalGroup(
            pnlSideBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideBodyLayout.createSequentialGroup()
                .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlFoot.setBackground(new java.awt.Color(0, 0, 0));
        pnlFoot.setPreferredSize(new java.awt.Dimension(256, 55));

        lblFoot.setFont(new java.awt.Font("Be Vietnam Pro", 1, 24)); // NOI18N
        lblFoot.setForeground(new java.awt.Color(255, 255, 255));
        lblFoot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFoot.setText("DOANH THU");

        javax.swing.GroupLayout pnlFootLayout = new javax.swing.GroupLayout(pnlFoot);
        pnlFoot.setLayout(pnlFootLayout);
        pnlFootLayout.setHorizontalGroup(
            pnlFootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFootLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(lblFoot, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFootLayout.setVerticalGroup(
            pnlFootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFoot, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlSidebarLayout = new javax.swing.GroupLayout(pnlSidebar);
        pnlSidebar.setLayout(pnlSidebarLayout);
        pnlSidebarLayout.setHorizontalGroup(
            pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSidebarLayout.createSequentialGroup()
                .addGroup(pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlSideBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(pnlFoot, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        pnlSidebarLayout.setVerticalGroup(
            pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSidebarLayout.createSequentialGroup()
                .addComponent(lblLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSideBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlFoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblExit.setFont(new java.awt.Font("Be Vietnam Pro", 1, 24)); // NOI18N
        lblExit.setForeground(new java.awt.Color(255, 255, 255));
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setText("x");
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });

        jtpDoanhThu.setFont(new java.awt.Font("Be Vietnam Pro", 0, 18)); // NOI18N

        pnlNgay.setBackground(new java.awt.Color(0, 204, 255));
        pnlNgay.setFont(new java.awt.Font("Be Vietnam Pro", 0, 15)); // NOI18N

        tblNgay.setFont(new java.awt.Font("Be Vietnam Pro", 0, 16)); // NOI18N
        tblNgay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NGÀY BÁN", "TỔNG SỐ BÀN", "TỔNG VÉ", "TỔNG TIỀN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNgay.setRowHeight(30);
        tblNgay.getTableHeader().setReorderingAllowed(false);
        jspNgay.setViewportView(tblNgay);

        btnXuatNgay.setBackground(new java.awt.Color(0, 80, 143));
        btnXuatNgay.setFont(new java.awt.Font("Be Vietnam Pro", 1, 22)); // NOI18N
        btnXuatNgay.setForeground(new java.awt.Color(255, 255, 255));
        btnXuatNgay.setText("XUẤT EXCEL");
        btnXuatNgay.setBorderPainted(false);
        btnXuatNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatNgayActionPerformed(evt);
            }
        });

        txtSearchNgay.setFont(new java.awt.Font("Be Vietnam Pro", 0, 20)); // NOI18N
        txtSearchNgay.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSearchNgay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchNgayKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlNgayLayout = new javax.swing.GroupLayout(pnlNgay);
        pnlNgay.setLayout(pnlNgayLayout);
        pnlNgayLayout.setHorizontalGroup(
            pnlNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNgayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNgayLayout.createSequentialGroup()
                        .addGap(0, 181, Short.MAX_VALUE)
                        .addGroup(pnlNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNgayLayout.createSequentialGroup()
                                .addComponent(txtSearchNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(181, 181, 181))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNgayLayout.createSequentialGroup()
                                .addComponent(btnXuatNgay)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNgayLayout.createSequentialGroup()
                        .addComponent(jspNgay)
                        .addContainerGap())))
        );
        pnlNgayLayout.setVerticalGroup(
            pnlNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNgayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearchNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspNgay, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnXuatNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jtpDoanhThu.addTab("DT NGÀY", new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-revenue.png")), pnlNgay); // NOI18N

        pnlThang.setBackground(new java.awt.Color(0, 204, 255));
        pnlThang.setFont(new java.awt.Font("Be Vietnam Pro", 0, 15)); // NOI18N

        tblThang.setFont(new java.awt.Font("Be Vietnam Pro", 0, 16)); // NOI18N
        tblThang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "THÁNG BÁN", "TỔNG SỐ BÀN", "TỔNG VÉ", "TỔNG TIỀN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblThang.setRowHeight(30);
        tblThang.getTableHeader().setReorderingAllowed(false);
        jspThang.setViewportView(tblThang);

        btnXuatThang.setBackground(new java.awt.Color(0, 80, 143));
        btnXuatThang.setFont(new java.awt.Font("Be Vietnam Pro", 1, 22)); // NOI18N
        btnXuatThang.setForeground(new java.awt.Color(255, 255, 255));
        btnXuatThang.setText("XUẤT EXCEL");
        btnXuatThang.setBorderPainted(false);
        btnXuatThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatThangActionPerformed(evt);
            }
        });

        txtSearchThang.setFont(new java.awt.Font("Be Vietnam Pro", 0, 20)); // NOI18N
        txtSearchThang.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSearchThang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchThangKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlThangLayout = new javax.swing.GroupLayout(pnlThang);
        pnlThang.setLayout(pnlThangLayout);
        pnlThangLayout.setHorizontalGroup(
            pnlThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThangLayout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(txtSearchThang, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
            .addGroup(pnlThangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThangLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnXuatThang))
                    .addComponent(jspThang))
                .addContainerGap())
        );
        pnlThangLayout.setVerticalGroup(
            pnlThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearchThang, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspThang, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnXuatThang, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jtpDoanhThu.addTab("DT THÁNG", new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-revenue.png")), pnlThang); // NOI18N

        pnlNam.setBackground(new java.awt.Color(0, 204, 255));
        pnlNam.setFont(new java.awt.Font("Be Vietnam Pro", 0, 15)); // NOI18N

        tblNam.setFont(new java.awt.Font("Be Vietnam Pro", 0, 16)); // NOI18N
        tblNam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NĂM BÁN", "TỔNG SỐ BÀN", "TỔNG VÉ", "TỔNG TIỀN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNam.setRowHeight(30);
        tblNam.getTableHeader().setReorderingAllowed(false);
        jspNam.setViewportView(tblNam);

        btnXuatNam.setBackground(new java.awt.Color(0, 80, 143));
        btnXuatNam.setFont(new java.awt.Font("Be Vietnam Pro", 1, 22)); // NOI18N
        btnXuatNam.setForeground(new java.awt.Color(255, 255, 255));
        btnXuatNam.setText("XUẤT EXCEL");
        btnXuatNam.setBorderPainted(false);
        btnXuatNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatNamActionPerformed(evt);
            }
        });

        txtSearchNam.setFont(new java.awt.Font("Be Vietnam Pro", 0, 20)); // NOI18N
        txtSearchNam.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSearchNam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchNamKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlNamLayout = new javax.swing.GroupLayout(pnlNam);
        pnlNam.setLayout(pnlNamLayout);
        pnlNamLayout.setHorizontalGroup(
            pnlNamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNamLayout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(txtSearchNam, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlNamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNamLayout.createSequentialGroup()
                        .addGap(0, 622, Short.MAX_VALUE)
                        .addComponent(btnXuatNam))
                    .addComponent(jspNam))
                .addContainerGap())
        );
        pnlNamLayout.setVerticalGroup(
            pnlNamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearchNam, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspNam, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnXuatNam, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jtpDoanhThu.addTab("DT NĂM", new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-revenue.png")), pnlNam); // NOI18N

        javax.swing.GroupLayout pblBanLayout = new javax.swing.GroupLayout(pblBan);
        pblBan.setLayout(pblBanLayout);
        pblBanLayout.setHorizontalGroup(
            pblBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pblBanLayout.createSequentialGroup()
                .addGroup(pblBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pblBanLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pblBanLayout.createSequentialGroup()
                        .addComponent(jtpDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addComponent(pnlSidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pblBanLayout.setVerticalGroup(
            pblBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pblBanLayout.createSequentialGroup()
                .addComponent(lblExit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtpDoanhThu))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pblBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pblBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_lblExitMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.showName();
        this.fillTableDTNgay();
        this.fillTableDTThang();
        this.fillTableDTNam();
    }//GEN-LAST:event_formWindowOpened

    private void btnXuatNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatNgayActionPerformed
        // TODO add your handling code here:
        XHelper.writeToExcel(tblNgay, "DOANH THU NGÀY");
    }//GEN-LAST:event_btnXuatNgayActionPerformed

    private void btnXuatThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatThangActionPerformed
        // TODO add your handling code here:
        XHelper.writeToExcel(tblThang, "DOANH THU THÁNG");
    }//GEN-LAST:event_btnXuatThangActionPerformed

    private void btnXuatNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatNamActionPerformed
        // TODO add your handling code here:
        XHelper.writeToExcel(tblNam, "DOANH THU NĂM");
    }//GEN-LAST:event_btnXuatNamActionPerformed

    private void txtSearchNamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchNamKeyReleased
        // TODO add your handling code here:
        XHelper.searchMultiple(tblNam, txtSearchNam);
    }//GEN-LAST:event_txtSearchNamKeyReleased

    private void txtSearchThangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchThangKeyReleased
        // TODO add your handling code here:
        XHelper.searchMultiple(tblThang, txtSearchThang);
    }//GEN-LAST:event_txtSearchThangKeyReleased

    private void txtSearchNgayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchNgayKeyReleased
        // TODO add your handling code here:
        XHelper.searchMultiple(tblNgay, txtSearchNgay);
    }//GEN-LAST:event_txtSearchNgayKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXuatNam;
    private javax.swing.JButton btnXuatNgay;
    private javax.swing.JButton btnXuatThang;
    private javax.swing.JScrollPane jspNam;
    private javax.swing.JScrollPane jspNgay;
    private javax.swing.JScrollPane jspThang;
    private javax.swing.JTabbedPane jtpDoanhThu;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblFoot;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblStaff;
    private javax.swing.JPanel pblBan;
    private javax.swing.JPanel pnlFoot;
    private javax.swing.JPanel pnlNam;
    private javax.swing.JPanel pnlNgay;
    private javax.swing.JPanel pnlSideBody;
    private javax.swing.JPanel pnlSidebar;
    private javax.swing.JPanel pnlStaff;
    private javax.swing.JPanel pnlThang;
    private javax.swing.JTable tblNam;
    private javax.swing.JTable tblNgay;
    private javax.swing.JTable tblThang;
    private javax.swing.JTextField txtSearchNam;
    private javax.swing.JTextField txtSearchNgay;
    private javax.swing.JTextField txtSearchThang;
    // End of variables declaration//GEN-END:variables
}
