package buffet.ui;

import buffet.model.HoaDon;
import buffet.ui.ban.FrmBanJD;
import buffet.ui.ban.FrmVeJD;
import com.formdev.flatlaf.FlatLightLaf;
import buffet.utils.XAuth;
import buffet.ui.ban.FrmHoaDonJD;
import buffet.ui.ban.FrmMonThemJD;
import buffet.ui.kho.FrmDoiTacJD;
import buffet.ui.kho.FrmKhoJD;
import buffet.utils.XDialog;
import buffet.utils.XHelper;
import buffet.utils.XMusic;
import java.awt.Color;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author duyplus
 */
public class MainUI extends javax.swing.JFrame {

    XMusic player = new XMusic();
    public static int count;

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
        init();
    }

    private void init() {
        setLocationRelativeTo(null);
        jspMenu.getVerticalScrollBar().setUnitIncrement(16);
        setIconImage(XHelper.getAppIcon());
        new FrmChaoJD(this, true).setVisible(true);
        new FrmDangNhapJD(this, true).setVisible(true);
    }

    private void openBan() {
        new FrmBanJD(this, true).setVisible(true);
    }

    private void openVe() {
        if (!XAuth.isManager()) {
            XDialog.alert(this, "Chỉ người quản lý mới có quyền truy cập!");
        } else {
            new FrmVeJD(this, true).setVisible(true);
        }
    }

    private void openHoaDon() {
        HoaDon hd = new HoaDon();
        DefaultTableModel model = new DefaultTableModel();
        new FrmHoaDonJD(this, true, hd, model).setVisible(true);
    }

    private void openMonThem() {
        new FrmMonThemJD(this, true).setVisible(true);
    }

    private void openNhanVien() {
        new FrmNhanVienJD(this, true).setVisible(true);
    }

    private void openCa() {
        new FrmCaJD(this, true).setVisible(true);
    }

    private void openDoanhThu() {
        if (!XAuth.isManager()) {
            XDialog.alert(this, "Chỉ người quản lý mới có quyền truy cập!");
        } else {
            new FrmDoanhThuJD(this, true).setVisible(true);
        }
    }

    private void openDoiTac() {
        new FrmDoiTacJD(this, true).setVisible(true);
    }

    private void openKho() {
        new FrmKhoJD(this, true).setVisible(true);
    }

    private void openNguoiDung() {
        new FrmNguoiDungJD(this, true).setVisible(true);
    }

    private void openKHTT() {
        new FrmKHTTJD(this, true).setVisible(true);
    }

    private void dangXuat() {
        XAuth.clear();
        JOptionPane.showMessageDialog(this, "Bạn đã đăng xuất\nVui lòng đăng nhập để sử dụng!");
        new FrmDangNhapJD(this, true).setVisible(true);
        this.showName();
    }

    private void setColor(javax.swing.JPanel panel) {
        panel.setBackground(new Color(253, 198, 149));
    }

    private void resetColor(javax.swing.JPanel panel) {
        panel.setBackground(new Color(253, 249, 222));
    }

    public void showName() {
        lblStaff.setText(XAuth.user.getTaiKhoan());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fc = new javax.swing.JFileChooser();
        pnlMain = new javax.swing.JPanel();
        pnlSidebar = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        pnlSideBody = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        pnlStaff = new javax.swing.JPanel();
        lblStaff = new javax.swing.JLabel();
        pnlFoot = new javax.swing.JPanel();
        lblFoot = new javax.swing.JLabel();
        pnlMusic = new javax.swing.JPanel();
        select = new javax.swing.JButton();
        play = new javax.swing.JButton();
        pause = new javax.swing.JButton();
        resume = new javax.swing.JButton();
        stop = new javax.swing.JButton();
        songName = new javax.swing.JLabel();
        loop = new javax.swing.JButton();
        jspMenu = new javax.swing.JScrollPane();
        pnlMenu = new javax.swing.JPanel();
        pnlBan = new javax.swing.JPanel();
        lblBan = new javax.swing.JLabel();
        pnlTable = new javax.swing.JPanel();
        lblTable = new javax.swing.JLabel();
        pnlVe = new javax.swing.JPanel();
        lblVe = new javax.swing.JLabel();
        pnlTicket = new javax.swing.JPanel();
        lblTicket = new javax.swing.JLabel();
        pnlHoaDon = new javax.swing.JPanel();
        lblHoaDon = new javax.swing.JLabel();
        pnlInvoice = new javax.swing.JPanel();
        lblInvoice = new javax.swing.JLabel();
        pnlNhanVien = new javax.swing.JPanel();
        lblNhanVien = new javax.swing.JLabel();
        pnlUsers = new javax.swing.JPanel();
        lblUsers = new javax.swing.JLabel();
        pnlCa = new javax.swing.JPanel();
        lblCa = new javax.swing.JLabel();
        pnlShift = new javax.swing.JPanel();
        lblShift = new javax.swing.JLabel();
        pnlMonThem = new javax.swing.JPanel();
        lblMonThem = new javax.swing.JLabel();
        pnlFood = new javax.swing.JPanel();
        lblFood = new javax.swing.JLabel();
        pnlNguoiDung = new javax.swing.JPanel();
        lblNguoiDung = new javax.swing.JLabel();
        pnlUser = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        pnlKHTT = new javax.swing.JPanel();
        lblKHTT = new javax.swing.JLabel();
        pnlCustumer = new javax.swing.JPanel();
        lblCustomer = new javax.swing.JLabel();
        pnlDoanhThu = new javax.swing.JPanel();
        lblDoanhThu = new javax.swing.JLabel();
        pnlStatistics = new javax.swing.JPanel();
        lblStatistics = new javax.swing.JLabel();
        pnlKho = new javax.swing.JPanel();
        lblKho = new javax.swing.JLabel();
        pnlWarehouse = new javax.swing.JPanel();
        lblWarehouse = new javax.swing.JLabel();
        pnlDoiTac = new javax.swing.JPanel();
        lblDoiTac = new javax.swing.JLabel();
        pnlPartner = new javax.swing.JPanel();
        lblPartner = new javax.swing.JLabel();
        pnlDangXuat = new javax.swing.JPanel();
        lblDangXuat = new javax.swing.JLabel();
        pnlLogout = new javax.swing.JPanel();
        lblLogout = new javax.swing.JLabel();
        pnlKetThuc = new javax.swing.JPanel();
        lblKetThuc = new javax.swing.JLabel();
        pnlClose = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();

        fc.setDialogTitle("Chọn logo chuyên đề");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ NHÀ HÀNG BUFFET");
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlMain.setBackground(new java.awt.Color(54, 180, 252));
        pnlMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlMain.setPreferredSize(new java.awt.Dimension(1028, 590));

        pnlSidebar.setBackground(new java.awt.Color(255, 255, 255));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo-app.png"))); // NOI18N

        pnlSideBody.setBackground(new java.awt.Color(255, 255, 255));

        lblIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-user.png"))); // NOI18N

        pnlStaff.setBackground(new java.awt.Color(255, 255, 255));
        pnlStaff.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lblStaff.setFont(new java.awt.Font("Be Vietnam Pro", 1, 30)); // NOI18N
        lblStaff.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlStaffLayout = new javax.swing.GroupLayout(pnlStaff);
        pnlStaff.setLayout(pnlStaffLayout);
        pnlStaffLayout.setHorizontalGroup(
            pnlStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStaffLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStaff, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlStaffLayout.setVerticalGroup(
            pnlStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStaffLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStaff, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlFoot.setBackground(new java.awt.Color(0, 0, 0));
        pnlFoot.setPreferredSize(new java.awt.Dimension(256, 55));

        lblFoot.setFont(new java.awt.Font("Be Vietnam Pro", 1, 24)); // NOI18N
        lblFoot.setForeground(new java.awt.Color(255, 255, 255));
        lblFoot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFoot.setText("XIN CHÀO");

        javax.swing.GroupLayout pnlFootLayout = new javax.swing.GroupLayout(pnlFoot);
        pnlFoot.setLayout(pnlFootLayout);
        pnlFootLayout.setHorizontalGroup(
            pnlFootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFootLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(lblFoot, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFootLayout.setVerticalGroup(
            pnlFootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFootLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFoot, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlMusic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        select.setFont(new java.awt.Font("Be Vietnam Pro", 0, 15)); // NOI18N
        select.setText("Select songs");
        select.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                selectMouseReleased(evt);
            }
        });

        play.setFont(new java.awt.Font("Be Vietnam Pro", 0, 15)); // NOI18N
        play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/button-play.png"))); // NOI18N
        play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                playMouseReleased(evt);
            }
        });

        pause.setFont(new java.awt.Font("Be Vietnam Pro", 0, 15)); // NOI18N
        pause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/button-pause.png"))); // NOI18N
        pause.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pauseMouseReleased(evt);
            }
        });

        resume.setFont(new java.awt.Font("Be Vietnam Pro", 0, 15)); // NOI18N
        resume.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/button-resume.png"))); // NOI18N
        resume.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                resumeMouseReleased(evt);
            }
        });

        stop.setFont(new java.awt.Font("Be Vietnam Pro", 0, 15)); // NOI18N
        stop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/button-stop.png"))); // NOI18N
        stop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                stopMouseReleased(evt);
            }
        });

        songName.setBackground(new java.awt.Color(255, 153, 51));
        songName.setFont(new java.awt.Font("Be Vietnam Pro", 0, 14)); // NOI18N
        songName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        loop.setFont(new java.awt.Font("Be Vietnam Pro", 0, 15)); // NOI18N
        loop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/button-repeat.png"))); // NOI18N
        loop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loopMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlMusicLayout = new javax.swing.GroupLayout(pnlMusic);
        pnlMusic.setLayout(pnlMusicLayout);
        pnlMusicLayout.setHorizontalGroup(
            pnlMusicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMusicLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMusicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(select, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlMusicLayout.createSequentialGroup()
                        .addComponent(play, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pause, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resume, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(loop, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stop, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(songName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlMusicLayout.setVerticalGroup(
            pnlMusicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMusicLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(select, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(songName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(pnlMusicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(play, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pause, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resume, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stop, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loop, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlSideBodyLayout = new javax.swing.GroupLayout(pnlSideBody);
        pnlSideBody.setLayout(pnlSideBodyLayout);
        pnlSideBodyLayout.setHorizontalGroup(
            pnlSideBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSideBodyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addComponent(pnlFoot, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
            .addComponent(lblIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlSideBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMusic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlSideBodyLayout.setVerticalGroup(
            pnlSideBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideBodyLayout.createSequentialGroup()
                .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlMusic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlFoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout pnlSidebarLayout = new javax.swing.GroupLayout(pnlSidebar);
        pnlSidebar.setLayout(pnlSidebarLayout);
        pnlSidebarLayout.setHorizontalGroup(
            pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSideBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlSidebarLayout.setVerticalGroup(
            pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSidebarLayout.createSequentialGroup()
                .addComponent(lblLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSideBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMenu.setBackground(new java.awt.Color(54, 180, 252));

        pnlBan.setBackground(new java.awt.Color(253, 249, 222));
        pnlBan.setPreferredSize(new java.awt.Dimension(170, 153));
        pnlBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlBanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlBanMouseExited(evt);
            }
        });

        lblBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-table-top-view.png"))); // NOI18N

        pnlTable.setBackground(new java.awt.Color(0, 51, 102));

        lblTable.setFont(new java.awt.Font("Be Vietnam Pro", 1, 22)); // NOI18N
        lblTable.setForeground(new java.awt.Color(255, 255, 255));
        lblTable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTable.setText("Bàn");

        javax.swing.GroupLayout pnlTableLayout = new javax.swing.GroupLayout(pnlTable);
        pnlTable.setLayout(pnlTableLayout);
        pnlTableLayout.setHorizontalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlTableLayout.setVerticalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlBanLayout = new javax.swing.GroupLayout(pnlBan);
        pnlBan.setLayout(pnlBanLayout);
        pnlBanLayout.setHorizontalGroup(
            pnlBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlBanLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblBan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBanLayout.setVerticalGroup(
            pnlBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBanLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblBan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlVe.setBackground(new java.awt.Color(253, 249, 222));
        pnlVe.setPreferredSize(new java.awt.Dimension(170, 153));
        pnlVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlVeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlVeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlVeMouseExited(evt);
            }
        });

        lblVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-ticket.png"))); // NOI18N

        pnlTicket.setBackground(new java.awt.Color(0, 51, 102));

        lblTicket.setFont(new java.awt.Font("Be Vietnam Pro", 1, 22)); // NOI18N
        lblTicket.setForeground(new java.awt.Color(255, 255, 255));
        lblTicket.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTicket.setText("Vé");

        javax.swing.GroupLayout pnlTicketLayout = new javax.swing.GroupLayout(pnlTicket);
        pnlTicket.setLayout(pnlTicketLayout);
        pnlTicketLayout.setHorizontalGroup(
            pnlTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTicket, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlTicketLayout.setVerticalGroup(
            pnlTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTicket, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlVeLayout = new javax.swing.GroupLayout(pnlVe);
        pnlVe.setLayout(pnlVeLayout);
        pnlVeLayout.setHorizontalGroup(
            pnlVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTicket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlVeLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblVe)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        pnlVeLayout.setVerticalGroup(
            pnlVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblVe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlHoaDon.setBackground(new java.awt.Color(253, 249, 222));
        pnlHoaDon.setPreferredSize(new java.awt.Dimension(170, 153));
        pnlHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlHoaDonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlHoaDonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlHoaDonMouseExited(evt);
            }
        });

        lblHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-bill.png"))); // NOI18N

        pnlInvoice.setBackground(new java.awt.Color(0, 51, 102));

        lblInvoice.setFont(new java.awt.Font("Be Vietnam Pro", 1, 22)); // NOI18N
        lblInvoice.setForeground(new java.awt.Color(255, 255, 255));
        lblInvoice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInvoice.setText("Hoá đơn");

        javax.swing.GroupLayout pnlInvoiceLayout = new javax.swing.GroupLayout(pnlInvoice);
        pnlInvoice.setLayout(pnlInvoiceLayout);
        pnlInvoiceLayout.setHorizontalGroup(
            pnlInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblInvoice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlInvoiceLayout.setVerticalGroup(
            pnlInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblInvoice, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlHoaDonLayout = new javax.swing.GroupLayout(pnlHoaDon);
        pnlHoaDon.setLayout(pnlHoaDonLayout);
        pnlHoaDonLayout.setHorizontalGroup(
            pnlHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlInvoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlHoaDonLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblHoaDon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHoaDonLayout.setVerticalGroup(
            pnlHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHoaDonLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblHoaDon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlNhanVien.setBackground(new java.awt.Color(253, 249, 222));
        pnlNhanVien.setPreferredSize(new java.awt.Dimension(170, 159));
        pnlNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlNhanVienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlNhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlNhanVienMouseExited(evt);
            }
        });

        lblNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-staff.png"))); // NOI18N

        pnlUsers.setBackground(new java.awt.Color(0, 51, 102));

        lblUsers.setFont(new java.awt.Font("Be Vietnam Pro", 1, 22)); // NOI18N
        lblUsers.setForeground(new java.awt.Color(255, 255, 255));
        lblUsers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsers.setText("Nhân viên");

        javax.swing.GroupLayout pnlUsersLayout = new javax.swing.GroupLayout(pnlUsers);
        pnlUsers.setLayout(pnlUsersLayout);
        pnlUsersLayout.setHorizontalGroup(
            pnlUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlUsersLayout.setVerticalGroup(
            pnlUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUsers, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlNhanVienLayout = new javax.swing.GroupLayout(pnlNhanVien);
        pnlNhanVien.setLayout(pnlNhanVienLayout);
        pnlNhanVienLayout.setHorizontalGroup(
            pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlNhanVienLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblNhanVien)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlNhanVienLayout.setVerticalGroup(
            pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNhanVienLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(lblNhanVien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlCa.setBackground(new java.awt.Color(253, 249, 222));
        pnlCa.setPreferredSize(new java.awt.Dimension(170, 153));
        pnlCa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlCaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlCaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlCaMouseExited(evt);
            }
        });

        lblCa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-change-user.png"))); // NOI18N

        pnlShift.setBackground(new java.awt.Color(0, 51, 102));

        lblShift.setFont(new java.awt.Font("Be Vietnam Pro", 1, 22)); // NOI18N
        lblShift.setForeground(new java.awt.Color(255, 255, 255));
        lblShift.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblShift.setText("Ca");

        javax.swing.GroupLayout pnlShiftLayout = new javax.swing.GroupLayout(pnlShift);
        pnlShift.setLayout(pnlShiftLayout);
        pnlShiftLayout.setHorizontalGroup(
            pnlShiftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblShift, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlShiftLayout.setVerticalGroup(
            pnlShiftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblShift, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlCaLayout = new javax.swing.GroupLayout(pnlCa);
        pnlCa.setLayout(pnlCaLayout);
        pnlCaLayout.setHorizontalGroup(
            pnlCaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlShift, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCa)
                .addGap(35, 35, 35))
        );
        pnlCaLayout.setVerticalGroup(
            pnlCaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlShift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlMonThem.setBackground(new java.awt.Color(253, 249, 222));
        pnlMonThem.setPreferredSize(new java.awt.Dimension(170, 153));
        pnlMonThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMonThemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlMonThemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlMonThemMouseExited(evt);
            }
        });

        lblMonThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-egg-basket.png"))); // NOI18N

        pnlFood.setBackground(new java.awt.Color(0, 51, 102));

        lblFood.setFont(new java.awt.Font("Be Vietnam Pro", 1, 22)); // NOI18N
        lblFood.setForeground(new java.awt.Color(255, 255, 255));
        lblFood.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFood.setText("Món thêm");

        javax.swing.GroupLayout pnlFoodLayout = new javax.swing.GroupLayout(pnlFood);
        pnlFood.setLayout(pnlFoodLayout);
        pnlFoodLayout.setHorizontalGroup(
            pnlFoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFood, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlFoodLayout.setVerticalGroup(
            pnlFoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFood, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlMonThemLayout = new javax.swing.GroupLayout(pnlMonThem);
        pnlMonThem.setLayout(pnlMonThemLayout);
        pnlMonThemLayout.setHorizontalGroup(
            pnlMonThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFood, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlMonThemLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblMonThem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMonThemLayout.setVerticalGroup(
            pnlMonThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMonThemLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMonThem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlFood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlNguoiDung.setBackground(new java.awt.Color(253, 249, 222));
        pnlNguoiDung.setPreferredSize(new java.awt.Dimension(170, 153));
        pnlNguoiDung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlNguoiDungMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlNguoiDungMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlNguoiDungMouseExited(evt);
            }
        });

        lblNguoiDung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-male-user.png"))); // NOI18N

        pnlUser.setBackground(new java.awt.Color(0, 51, 102));

        lblUser.setFont(new java.awt.Font("Be Vietnam Pro", 1, 22)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUser.setText("Người dùng");

        javax.swing.GroupLayout pnlUserLayout = new javax.swing.GroupLayout(pnlUser);
        pnlUser.setLayout(pnlUserLayout);
        pnlUserLayout.setHorizontalGroup(
            pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlUserLayout.setVerticalGroup(
            pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlNguoiDungLayout = new javax.swing.GroupLayout(pnlNguoiDung);
        pnlNguoiDung.setLayout(pnlNguoiDungLayout);
        pnlNguoiDungLayout.setHorizontalGroup(
            pnlNguoiDungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNguoiDungLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblNguoiDung)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        pnlNguoiDungLayout.setVerticalGroup(
            pnlNguoiDungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNguoiDungLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblNguoiDung)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlKHTT.setBackground(new java.awt.Color(253, 249, 222));
        pnlKHTT.setPreferredSize(new java.awt.Dimension(170, 153));
        pnlKHTT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlKHTTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlKHTTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlKHTTMouseExited(evt);
            }
        });

        lblKHTT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-hornbill.png"))); // NOI18N

        pnlCustumer.setBackground(new java.awt.Color(0, 51, 102));

        lblCustomer.setFont(new java.awt.Font("Be Vietnam Pro", 1, 22)); // NOI18N
        lblCustomer.setForeground(new java.awt.Color(255, 255, 255));
        lblCustomer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCustomer.setText("KHTT");

        javax.swing.GroupLayout pnlCustumerLayout = new javax.swing.GroupLayout(pnlCustumer);
        pnlCustumer.setLayout(pnlCustumerLayout);
        pnlCustumerLayout.setHorizontalGroup(
            pnlCustumerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlCustumerLayout.setVerticalGroup(
            pnlCustumerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlKHTTLayout = new javax.swing.GroupLayout(pnlKHTT);
        pnlKHTT.setLayout(pnlKHTTLayout);
        pnlKHTTLayout.setHorizontalGroup(
            pnlKHTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCustumer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKHTTLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(lblKHTT)
                .addGap(35, 35, 35))
        );
        pnlKHTTLayout.setVerticalGroup(
            pnlKHTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKHTTLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblKHTT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlCustumer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlDoanhThu.setBackground(new java.awt.Color(253, 249, 222));
        pnlDoanhThu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlDoanhThuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlDoanhThuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlDoanhThuMouseExited(evt);
            }
        });

        lblDoanhThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-get-revenue.png"))); // NOI18N

        pnlStatistics.setBackground(new java.awt.Color(0, 51, 102));

        lblStatistics.setFont(new java.awt.Font("Be Vietnam Pro", 1, 22)); // NOI18N
        lblStatistics.setForeground(new java.awt.Color(255, 255, 255));
        lblStatistics.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatistics.setText("Doanh thu");

        javax.swing.GroupLayout pnlStatisticsLayout = new javax.swing.GroupLayout(pnlStatistics);
        pnlStatistics.setLayout(pnlStatisticsLayout);
        pnlStatisticsLayout.setHorizontalGroup(
            pnlStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblStatistics, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlStatisticsLayout.setVerticalGroup(
            pnlStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblStatistics, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlDoanhThuLayout = new javax.swing.GroupLayout(pnlDoanhThu);
        pnlDoanhThu.setLayout(pnlDoanhThuLayout);
        pnlDoanhThuLayout.setHorizontalGroup(
            pnlDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlStatistics, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlDoanhThuLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblDoanhThu)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        pnlDoanhThuLayout.setVerticalGroup(
            pnlDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDoanhThuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDoanhThu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlStatistics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlKho.setBackground(new java.awt.Color(253, 249, 222));
        pnlKho.setPreferredSize(new java.awt.Dimension(170, 153));
        pnlKho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlKhoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlKhoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlKhoMouseExited(evt);
            }
        });

        lblKho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-warehouse.png"))); // NOI18N

        pnlWarehouse.setBackground(new java.awt.Color(0, 51, 102));

        lblWarehouse.setFont(new java.awt.Font("Be Vietnam Pro", 1, 22)); // NOI18N
        lblWarehouse.setForeground(new java.awt.Color(255, 255, 255));
        lblWarehouse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWarehouse.setText("Kho");

        javax.swing.GroupLayout pnlWarehouseLayout = new javax.swing.GroupLayout(pnlWarehouse);
        pnlWarehouse.setLayout(pnlWarehouseLayout);
        pnlWarehouseLayout.setHorizontalGroup(
            pnlWarehouseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblWarehouse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlWarehouseLayout.setVerticalGroup(
            pnlWarehouseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblWarehouse, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlKhoLayout = new javax.swing.GroupLayout(pnlKho);
        pnlKho.setLayout(pnlKhoLayout);
        pnlKhoLayout.setHorizontalGroup(
            pnlKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlWarehouse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKhoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblKho)
                .addGap(35, 35, 35))
        );
        pnlKhoLayout.setVerticalGroup(
            pnlKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKhoLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(lblKho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlWarehouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlDoiTac.setBackground(new java.awt.Color(253, 249, 222));
        pnlDoiTac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlDoiTacMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlDoiTacMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlDoiTacMouseExited(evt);
            }
        });

        lblDoiTac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-handshake.png"))); // NOI18N

        pnlPartner.setBackground(new java.awt.Color(0, 51, 102));

        lblPartner.setFont(new java.awt.Font("Be Vietnam Pro", 1, 22)); // NOI18N
        lblPartner.setForeground(new java.awt.Color(255, 255, 255));
        lblPartner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPartner.setText("Đối tác");

        javax.swing.GroupLayout pnlPartnerLayout = new javax.swing.GroupLayout(pnlPartner);
        pnlPartner.setLayout(pnlPartnerLayout);
        pnlPartnerLayout.setHorizontalGroup(
            pnlPartnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPartner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlPartnerLayout.setVerticalGroup(
            pnlPartnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPartner, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlDoiTacLayout = new javax.swing.GroupLayout(pnlDoiTac);
        pnlDoiTac.setLayout(pnlDoiTacLayout);
        pnlDoiTacLayout.setHorizontalGroup(
            pnlDoiTacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPartner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDoiTacLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblDoiTac)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        pnlDoiTacLayout.setVerticalGroup(
            pnlDoiTacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDoiTacLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDoiTac)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlPartner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlDangXuat.setBackground(new java.awt.Color(253, 249, 222));
        pnlDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlDangXuatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlDangXuatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlDangXuatMouseExited(evt);
            }
        });

        lblDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-logout.png"))); // NOI18N

        pnlLogout.setBackground(new java.awt.Color(0, 51, 102));

        lblLogout.setFont(new java.awt.Font("Be Vietnam Pro", 1, 22)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(255, 255, 255));
        lblLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogout.setText("Đăng xuất");

        javax.swing.GroupLayout pnlLogoutLayout = new javax.swing.GroupLayout(pnlLogout);
        pnlLogout.setLayout(pnlLogoutLayout);
        pnlLogoutLayout.setHorizontalGroup(
            pnlLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlLogoutLayout.setVerticalGroup(
            pnlLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlDangXuatLayout = new javax.swing.GroupLayout(pnlDangXuat);
        pnlDangXuat.setLayout(pnlDangXuatLayout);
        pnlDangXuatLayout.setHorizontalGroup(
            pnlDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDangXuatLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblDangXuat)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        pnlDangXuatLayout.setVerticalGroup(
            pnlDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDangXuatLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(lblDangXuat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlKetThuc.setBackground(new java.awt.Color(253, 249, 222));
        pnlKetThuc.setPreferredSize(new java.awt.Dimension(170, 153));
        pnlKetThuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlKetThucMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlKetThucMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlKetThucMouseExited(evt);
            }
        });

        lblKetThuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-shutdown.png"))); // NOI18N

        pnlClose.setBackground(new java.awt.Color(0, 51, 102));

        lblClose.setFont(new java.awt.Font("Be Vietnam Pro", 1, 22)); // NOI18N
        lblClose.setForeground(new java.awt.Color(255, 255, 255));
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("Kết thúc");

        javax.swing.GroupLayout pnlCloseLayout = new javax.swing.GroupLayout(pnlClose);
        pnlClose.setLayout(pnlCloseLayout);
        pnlCloseLayout.setHorizontalGroup(
            pnlCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblClose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlCloseLayout.setVerticalGroup(
            pnlCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblClose, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlKetThucLayout = new javax.swing.GroupLayout(pnlKetThuc);
        pnlKetThuc.setLayout(pnlKetThucLayout);
        pnlKetThucLayout.setHorizontalGroup(
            pnlKetThucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKetThucLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblKetThuc)
                .addGap(35, 35, 35))
        );
        pnlKetThucLayout.setVerticalGroup(
            pnlKetThucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKetThucLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(lblKetThuc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pnlNguoiDung, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlBan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlNhanVien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlKho, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(pnlCa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pnlVe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(pnlDoiTac, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlKHTT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE))
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addComponent(pnlDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlDoanhThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlMonThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlKetThuc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pnlVe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(pnlBan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(pnlHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pnlCa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(pnlNhanVien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlMonThem, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pnlDoanhThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlNguoiDung, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(pnlKHTT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pnlDoiTac, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlKho, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)))
                    .addComponent(pnlKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(pnlDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jspMenu.setViewportView(pnlMenu);

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(jspMenu)
                .addGap(0, 0, 0)
                .addComponent(pnlSidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(pnlSidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 1170, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlBanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBanMouseClicked
        // TODO add your handling code here:
        this.openBan();
    }//GEN-LAST:event_pnlBanMouseClicked

    private void pnlBanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBanMouseEntered
        // TODO add your handling code here:
        setColor(pnlBan);
    }//GEN-LAST:event_pnlBanMouseEntered

    private void pnlBanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBanMouseExited
        // TODO add your handling code here:
        resetColor(pnlBan);
    }//GEN-LAST:event_pnlBanMouseExited

    private void pnlVeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlVeMouseClicked
        // TODO add your handling code here:
        this.openVe();
    }//GEN-LAST:event_pnlVeMouseClicked

    private void pnlVeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlVeMouseEntered
        // TODO add your handling code here:
        setColor(pnlVe);
    }//GEN-LAST:event_pnlVeMouseEntered

    private void pnlVeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlVeMouseExited
        // TODO add your handling code here:
        resetColor(pnlVe);
    }//GEN-LAST:event_pnlVeMouseExited

    private void pnlHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHoaDonMouseClicked
        // TODO add your handling code here:
        this.openHoaDon();
    }//GEN-LAST:event_pnlHoaDonMouseClicked

    private void pnlHoaDonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHoaDonMouseEntered
        // TODO add your handling code here:
        setColor(pnlHoaDon);
    }//GEN-LAST:event_pnlHoaDonMouseEntered

    private void pnlHoaDonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHoaDonMouseExited
        // TODO add your handling code here:
        resetColor(pnlHoaDon);
    }//GEN-LAST:event_pnlHoaDonMouseExited

    private void pnlNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNhanVienMouseClicked
        // TODO add your handling code here:
        this.openNhanVien();
    }//GEN-LAST:event_pnlNhanVienMouseClicked

    private void pnlNhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNhanVienMouseEntered
        // TODO add your handling code here:
        setColor(pnlNhanVien);
    }//GEN-LAST:event_pnlNhanVienMouseEntered

    private void pnlNhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNhanVienMouseExited
        // TODO add your handling code here:
        resetColor(pnlNhanVien);
    }//GEN-LAST:event_pnlNhanVienMouseExited

    private void pnlDoanhThuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDoanhThuMouseClicked
        // TODO add your handling code here:
        this.openDoanhThu();
    }//GEN-LAST:event_pnlDoanhThuMouseClicked

    private void pnlDoanhThuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDoanhThuMouseEntered
        // TODO add your handling code here:
        setColor(pnlDoanhThu);
    }//GEN-LAST:event_pnlDoanhThuMouseEntered

    private void pnlDoanhThuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDoanhThuMouseExited
        // TODO add your handling code here:
        resetColor(pnlDoanhThu);
    }//GEN-LAST:event_pnlDoanhThuMouseExited

    private void pnlDoiTacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDoiTacMouseClicked
        // TODO add your handling code here:
        this.openDoiTac();
    }//GEN-LAST:event_pnlDoiTacMouseClicked

    private void pnlDoiTacMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDoiTacMouseEntered
        // TODO add your handling code here:
        setColor(pnlDoiTac);
    }//GEN-LAST:event_pnlDoiTacMouseEntered

    private void pnlDoiTacMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDoiTacMouseExited
        // TODO add your handling code here:
        resetColor(pnlDoiTac);
    }//GEN-LAST:event_pnlDoiTacMouseExited

    private void pnlCaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCaMouseClicked
        // TODO add your handling code here:
        this.openCa();
    }//GEN-LAST:event_pnlCaMouseClicked

    private void pnlCaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCaMouseEntered
        // TODO add your handling code here:
        setColor(pnlCa);
    }//GEN-LAST:event_pnlCaMouseEntered

    private void pnlCaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCaMouseExited
        // TODO add your handling code here:
        resetColor(pnlCa);
    }//GEN-LAST:event_pnlCaMouseExited

    private void pnlDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDangXuatMouseClicked
        // TODO add your handling code here:
        this.dangXuat();
    }//GEN-LAST:event_pnlDangXuatMouseClicked

    private void pnlDangXuatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDangXuatMouseEntered
        // TODO add your handling code here:
        setColor(pnlDangXuat);
    }//GEN-LAST:event_pnlDangXuatMouseEntered

    private void pnlDangXuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDangXuatMouseExited
        // TODO add your handling code here:
        resetColor(pnlDangXuat);
    }//GEN-LAST:event_pnlDangXuatMouseExited

    private void pnlKetThucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKetThucMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_pnlKetThucMouseClicked

    private void pnlKetThucMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKetThucMouseEntered
        // TODO add your handling code here:
        setColor(pnlKetThuc);
    }//GEN-LAST:event_pnlKetThucMouseEntered

    private void pnlKetThucMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKetThucMouseExited
        // TODO add your handling code here:
        resetColor(pnlKetThuc);
    }//GEN-LAST:event_pnlKetThucMouseExited

    private void pnlNguoiDungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNguoiDungMouseClicked
        // TODO add your handling code here:
        this.openNguoiDung();
    }//GEN-LAST:event_pnlNguoiDungMouseClicked

    private void pnlNguoiDungMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNguoiDungMouseEntered
        // TODO add your handling code here:
        setColor(pnlNguoiDung);
    }//GEN-LAST:event_pnlNguoiDungMouseEntered

    private void pnlNguoiDungMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNguoiDungMouseExited
        // TODO add your handling code here:
        resetColor(pnlNguoiDung);
    }//GEN-LAST:event_pnlNguoiDungMouseExited

    private void pnlKHTTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKHTTMouseExited
        // TODO add your handling code here:
        resetColor(pnlKHTT);
    }//GEN-LAST:event_pnlKHTTMouseExited

    private void pnlKHTTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKHTTMouseEntered
        // TODO add your handling code here:
        setColor(pnlKHTT);
    }//GEN-LAST:event_pnlKHTTMouseEntered

    private void pnlKHTTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKHTTMouseClicked
        // TODO add your handling code here:
        this.openKHTT();
    }//GEN-LAST:event_pnlKHTTMouseClicked

    private void pnlMonThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMonThemMouseClicked
        // TODO add your handling code here:
        this.openMonThem();
    }//GEN-LAST:event_pnlMonThemMouseClicked

    private void pnlMonThemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMonThemMouseEntered
        // TODO add your handling code here:
        setColor(pnlMonThem);
    }//GEN-LAST:event_pnlMonThemMouseEntered

    private void pnlMonThemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMonThemMouseExited
        // TODO add your handling code here:
        resetColor(pnlMonThem);
    }//GEN-LAST:event_pnlMonThemMouseExited

    private void pnlKhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKhoMouseClicked
        // TODO add your handling code here:
        this.openKho();
    }//GEN-LAST:event_pnlKhoMouseClicked

    private void pnlKhoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKhoMouseEntered
        // TODO add your handling code here:
        setColor(pnlKho);
    }//GEN-LAST:event_pnlKhoMouseEntered

    private void pnlKhoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKhoMouseExited
        // TODO add your handling code here:
        resetColor(pnlKho);
    }//GEN-LAST:event_pnlKhoMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.showName();
    }//GEN-LAST:event_formWindowOpened

    private void selectMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectMouseReleased
        // TODO add your handling code here:
        fc = new JFileChooser();
        fc.setDialogTitle("Select Mp3");
        fc.setCurrentDirectory(new File("C:\\Users"));
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.setFileFilter(new FileNameExtensionFilter("MP3 Files", "mp3", "mpeg3"));
        int returnVal = fc.showOpenDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            player.Stop();
            File myFile = fc.getSelectedFile();
            song = myFile + "";
            name = fc.getSelectedFile().getName();
            songName.setText("Song: " + name);
        }
    }//GEN-LAST:event_selectMouseReleased
    String song, name;
    private void playMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playMouseReleased
        // TODO add your handling code here:
        songName.setText("Playing: " + name);
        player.Play(song);
    }//GEN-LAST:event_playMouseReleased

    private void pauseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pauseMouseReleased
        // TODO add your handling code here:
        songName.setText("Pause: " + name);
        player.Pause();
    }//GEN-LAST:event_pauseMouseReleased

    private void resumeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resumeMouseReleased
        // TODO add your handling code here:
        songName.setText("Resume: " + name);
        player.Resume();
    }//GEN-LAST:event_resumeMouseReleased

    private void stopMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stopMouseReleased
        // TODO add your handling code here:
        songName.setText("");
        player.Stop();
    }//GEN-LAST:event_stopMouseReleased

    private void loopMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loopMouseReleased
        // TODO add your handling code here:
        switch (count) {
            case 0:
                songName.setText("Loop on: " + name);
                count = 1;
                break;
            case 1:
                songName.setText("Loop off: " + name);
                count = 0;
                break;
        }
    }//GEN-LAST:event_loopMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            javax.swing.UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser fc;
    private javax.swing.JScrollPane jspMenu;
    private javax.swing.JLabel lblBan;
    private javax.swing.JLabel lblCa;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblCustomer;
    private javax.swing.JLabel lblDangXuat;
    private javax.swing.JLabel lblDoanhThu;
    private javax.swing.JLabel lblDoiTac;
    private javax.swing.JLabel lblFood;
    private javax.swing.JLabel lblFoot;
    private javax.swing.JLabel lblHoaDon;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblInvoice;
    private javax.swing.JLabel lblKHTT;
    private javax.swing.JLabel lblKetThuc;
    private javax.swing.JLabel lblKho;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblMonThem;
    private javax.swing.JLabel lblNguoiDung;
    private javax.swing.JLabel lblNhanVien;
    private javax.swing.JLabel lblPartner;
    private javax.swing.JLabel lblShift;
    private javax.swing.JLabel lblStaff;
    private javax.swing.JLabel lblStatistics;
    private javax.swing.JLabel lblTable;
    private javax.swing.JLabel lblTicket;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblUsers;
    private javax.swing.JLabel lblVe;
    private javax.swing.JLabel lblWarehouse;
    private javax.swing.JButton loop;
    private javax.swing.JButton pause;
    private javax.swing.JButton play;
    private javax.swing.JPanel pnlBan;
    private javax.swing.JPanel pnlCa;
    private javax.swing.JPanel pnlClose;
    private javax.swing.JPanel pnlCustumer;
    private javax.swing.JPanel pnlDangXuat;
    private javax.swing.JPanel pnlDoanhThu;
    private javax.swing.JPanel pnlDoiTac;
    private javax.swing.JPanel pnlFood;
    private javax.swing.JPanel pnlFoot;
    private javax.swing.JPanel pnlHoaDon;
    private javax.swing.JPanel pnlInvoice;
    private javax.swing.JPanel pnlKHTT;
    private javax.swing.JPanel pnlKetThuc;
    private javax.swing.JPanel pnlKho;
    private javax.swing.JPanel pnlLogout;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlMonThem;
    private javax.swing.JPanel pnlMusic;
    private javax.swing.JPanel pnlNguoiDung;
    private javax.swing.JPanel pnlNhanVien;
    private javax.swing.JPanel pnlPartner;
    private javax.swing.JPanel pnlShift;
    private javax.swing.JPanel pnlSideBody;
    private javax.swing.JPanel pnlSidebar;
    private javax.swing.JPanel pnlStaff;
    private javax.swing.JPanel pnlStatistics;
    private javax.swing.JPanel pnlTable;
    private javax.swing.JPanel pnlTicket;
    private javax.swing.JPanel pnlUser;
    private javax.swing.JPanel pnlUsers;
    private javax.swing.JPanel pnlVe;
    private javax.swing.JPanel pnlWarehouse;
    private javax.swing.JButton resume;
    private javax.swing.JButton select;
    public static javax.swing.JLabel songName;
    private javax.swing.JButton stop;
    // End of variables declaration//GEN-END:variables
}
